libopencm3: USB
USB
LM4F
libopencm3 LM4F Universal Serial Bus controller
Macros
#define MAX_FIFO_RAM (4 * 1024)
Functions
void usb_enable_interrupts (enum usb_interrupt ints, enum usb_ep_interrupt rx_ints, enum usb_ep_interrupt tx_ints)
Enable Specific USB Interrupts.
void usb_disable_interrupts (enum usb_interrupt ints, enum usb_ep_interrupt rx_ints, enum usb_ep_interrupt tx_ints)
Disable Specific USB Interrupts.
Variables
const struct _usbd_driver lm4f_usb_driver
Detailed Description
libopencm3 LM4F Universal Serial Bus controller
Author
© 2013 Alexandru Gagniuc mr.nu.nosp@m.ke.m.nosp@m.e@gma.nosp@m.il.c.nosp@m.om
The LM4F USB driver is integrated with the libopencm3 USB stack. You should use the generic stack.
To use this driver, tell the linker to look for it:
extern usbd_driver lm4f_usb_driver;
And pass this driver as an argument when initializing the USB stack:
usbd_device *usbd_dev;
usbd_dev = usbd_init(&lm4f_usb_driver, ...);
Polling or interrupt-driven?
The LM4F USB driver will work fine regardless of whether it is called from an interrupt service routine, or from the main program loop.
Polling USB from the main loop requires calling usbd_poll() from the main program loop. For example:
// Main program loop
while(1) {
   usbd_poll(usb_dev);
   do_other_stuff();
   ...
Running usbd_poll() from an interrupt has the advantage that it is only called when needed, saving CPU cycles for the main program.
RESET, DISCON, RESUME, and SUSPEND interrupts must be enabled, along with the interrupts for any endpoint that is used. The EP0_TX interrupt must be enabled for the control endpoint to function correctly. For example, if EP1IN and EP2OUT are used, then the EP0_TX, EP1_TX, and EP2_RX interrupts should be enabled:
// Enable USB interrupts for EP0, EP1IN, and EP2OUT
ints = USB_INT_RESET | USB_INT_DISCON | USB_INT_RESUME |
    USB_INT_SUSPEND;
usb_enable_interrupts(ints, USB_EP2_INT, USB_EP0_INT | USB_EP1_INT);
// Route the interrupts through the NVIC
nvic_enable_irq(NVIC_USB0_IRQ);
The USB ISR only has to call usbd_poll().
void usb0_isr(void)
{
   usbd_poll(usb_dev);
}
Macro Definition Documentation
MAX_FIFO_RAM
#define MAX_FIFO_RAM (4 * 1024)
Definition at line 111 of file usb_lm4f.c.
Referenced by usb_disable_interrupts().
Function Documentation
usb_disable_interrupts()
void usb_disable_interrupts (enum usb_interrupt ints, enum usb_ep_interrupt rx_ints, enum usb_ep_interrupt tx_ints)
Disable Specific USB Interrupts.
Disable any combination of interrupts. Interrupts may be OR'ed together to enable them with one call. For example, to disable both the RESUME and RESET interrupts, pass (USB_INT_RESUME | USB_INT_RESET)
Note that the NVIC must be enabled and properly configured for the interrupt to be routed to the CPU.
Parameters
[in] ints Interrupts which to disable. Any combination of interrupts may be specified by OR'ing then together
[in] rx_ints Endpoints for which to stop generating an interrupt when a packet packet is received.
[in] tx_ints Endpoints for which to stop generating an interrupt when a packet packet is finished transmitting.
Definition at line 158 of file usb_lm4f.c.
References _usbd_reset(), lm4f_usb_driver, MAX_FIFO_RAM, periph_clock_enable(), RCC_USB0, rcc_usb_pll_on(), SYSCTL_IMC, SYSCTL_IMC_PLLLIM, SYSCTL_IMC_USBPLLLIM, SYSCTL_RIS, SYSCTL_RIS_USBPLLLRIS, SYSCTL_SRUSB, USB_BASE, USB_CSRL0, USB_CSRL0_DATAEND, USB_CSRL0_RXRDY, USB_CSRL0_RXRDYC, USB_CSRL0_STALL, USB_CSRL0_STALLED, USB_CSRL0_TXRDY, USB_ENDPOINT_ATTR_ISOCHRONOUS, USB_EP0, USB_EPIDX, USB_EPIDX_MASK, USB_FADDR, USB_FADDR_FUNCADDR_MASK, USB_FIFO16, USB_FIFO32, USB_FIFO8, USB_FIFOSZ_SIZE_1024, USB_FIFOSZ_SIZE_128, USB_FIFOSZ_SIZE_16, USB_FIFOSZ_SIZE_2048, USB_FIFOSZ_SIZE_256, USB_FIFOSZ_SIZE_32, USB_FIFOSZ_SIZE_512, USB_FIFOSZ_SIZE_64, USB_FIFOSZ_SIZE_8, USB_IE, USB_IM_RESET, USB_IM_RESUME, USB_IM_SOF, USB_IM_SUSPEND, USB_IS, USB_POWER, USB_POWER_SOFTCONN, USB_RXCOUNT, USB_RXCSRH, USB_RXCSRH_ISO, USB_RXCSRL, USB_RXCSRL_RXRDY, USB_RXCSRL_STALL, USB_RXCSRL_STALLED, USB_RXFIFOADD, USB_RXFIFOSZ, USB_RXIE, USB_RXIS, USB_RXMAXP, USB_TXCSRH, USB_TXCSRH_ISO, USB_TXCSRL, USB_TXCSRL_STALL, USB_TXCSRL_STALLED, USB_TXCSRL_TXRDY, USB_TXFIFOADD, USB_TXFIFOSZ, USB_TXIE, USB_TXIS, and USB_TXMAXP.
usb_enable_interrupts()
void usb_enable_interrupts (enum usb_interrupt ints, enum usb_ep_interrupt rx_ints, enum usb_ep_interrupt tx_ints)
Enable Specific USB Interrupts.
Enable any combination of interrupts. Interrupts may be OR'ed together to enable them with one call. For example, to enable both the RESUME and RESET interrupts, pass (USB_INT_RESUME | USB_INT_RESET)
Note that the NVIC must be enabled and properly configured for the interrupt to be routed to the CPU.
Parameters
[in] ints Interrupts which to enable. Any combination of interrupts may be specified by OR'ing then together
[in] rx_ints Endpoints for which to generate an interrupt when a packet packet is received.
[in] tx_ints Endpoints for which to generate an interrupt when a packet packet is finished transmitting.
Definition at line 132 of file usb_lm4f.c.
References USB_IE, USB_RXIE, and USB_TXIE.
Variable Documentation
lm4f_usb_driver
const struct _usbd_driver lm4f_usb_driver
Definition at line 113 of file usb_lm4f.c.
Referenced by usb_disable_interrupts().